name: Practicing workflow for pushing Docker image to Dockerhub

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: login into Dockerhub
        env:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

        run: docker login -u "$username" -p "$password"

      - name: build Docker image
        run: docker build -t $username/hello-docker:latest .

      - name: push Docker image
        run: docker push $username/hello-docker:latest


      


